# Generated by Django 5.0.6 on 2024-06-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'платеж', 'verbose_name_plural': 'платежи'},
        ),
    ]
