# Generated by Django 4.2.13 on 2024-07-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='sum',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'наличные'), ('transaction', 'перевод на счет')], default='transaction', max_length=20, verbose_name='способ оплаты'),
        ),
    ]
