# Generated by Django 4.2.13 on 2024-07-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_payment_sum_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='статус платежа'),
        ),
    ]
