# Generated by Django 5.0.6 on 2024-06-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='lesson/', verbose_name='превью (картинка)'),
        ),
    ]
