# Generated by Django 4.2.13 on 2024-07-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_course_amount_alter_lesson_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default='2024-05-06 09:39:35.72751+05', verbose_name='дата создания'),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(default='2024-05-06 09:39:35.72751+05', editable=False, verbose_name='дата обновления'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(default='2024-05-06 09:39:35.72751+05', verbose_name='дата создания'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(default='2024-05-06 09:39:35.72751+05', editable=False, verbose_name='дата обновления'),
        ),
    ]
